"""empty message

Revision ID: 350d8c01a685
Revises: c0b33771d559
Create Date: 2023-05-22 20:04:43.574967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350d8c01a685'
down_revision = 'c0b33771d559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=90), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
