"""empty message

Revision ID: c0b33771d559
Revises: 2bdd4202513e
Create Date: 2023-05-20 10:36:24.967282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b33771d559'
down_revision = '2bdd4202513e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operacao', sa.Column('conta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'operacao', 'conta', ['conta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operacao', type_='foreignkey')
    op.drop_column('operacao', 'conta_id')
    # ### end Alembic commands ###
